// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD99Ox1DKD8-QIiXF_3tVWP_NhdNgnK-wI',
    appId: '1:140169647078:web:a9b1d6d250cec004597c27',
    messagingSenderId: '140169647078',
    projectId: 'flutter-mvvm-gamer',
    authDomain: 'flutter-mvvm-gamer.firebaseapp.com',
    storageBucket: 'flutter-mvvm-gamer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG2QJ9ATsDJQOhrfS3yLZ7SV7bjKWk7gw',
    appId: '1:140169647078:android:961277afbda91d7e597c27',
    messagingSenderId: '140169647078',
    projectId: 'flutter-mvvm-gamer',
    storageBucket: 'flutter-mvvm-gamer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABZZFzTHpLTHE41N6GEiqQ00GvpsFM_tI',
    appId: '1:140169647078:ios:038b97429540910c597c27',
    messagingSenderId: '140169647078',
    projectId: 'flutter-mvvm-gamer',
    storageBucket: 'flutter-mvvm-gamer.appspot.com',
    iosClientId: '140169647078-7rst6rgbg3netcdhtd6bgl98un2q7eiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGamerMvvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABZZFzTHpLTHE41N6GEiqQ00GvpsFM_tI',
    appId: '1:140169647078:ios:52284df52d71e09e597c27',
    messagingSenderId: '140169647078',
    projectId: 'flutter-mvvm-gamer',
    storageBucket: 'flutter-mvvm-gamer.appspot.com',
    iosClientId: '140169647078-e71aasp0ijq68ngndtgbhfu57au9upir.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGamerMvvm.RunnerTests',
  );
}
